theme = "kanagawa"
editor.indent-guides.render = true
editor.auto-pairs = false
editor.auto-format = false
editor.idle-timeout = 0
editor.bufferline = "multiple"
editor.soft-wrap.enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
"'" = ":w"


[keys.normal." "]
f = "file_picker_in_current_directory"
F = "file_picker"
